services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=idiomax_db      
    networks:  
      - app_network

  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   working_dir: /app/apps/api
  #   ports:
  #     - "3030:3030"
  #     - "5555:5555"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgres://docker:docker@pg:5432/idiomax_db
  #   depends_on:
  #     - pg
  #   command: ["sh", "./start.sh"]

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./apps/app/Dockerfile
  #   container_name: app
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - .:/app 
  #     - /app/apps/app/node_modules 
  #     - /app/node_modules 
  #     - /app/packages/ui/node_modules 
  #     - /app/packages/utils/node_modules 
  #   networks:
  #     - app_network
      
  # landing-page:
  #   build:
  #     context: .
  #     dockerfile: ./apps/landing-page/Dockerfile
  #   container_name: landing-page
  #   ports:
  #     - "5174:5174"
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - .:/app 
  #     - /app/apps/landing-page/node_modules 
  #     - /app/node_modules 
  #     - /app/packages/ui/node_modules 
  #     - /app/packages/utils/node_modules 
  #   networks:
  #     - app_network

networks:
  app_network:
    external: true
